pipeline {
    agent any

    stages {

        stage('Test') {
            steps {
                sh 'echo "Ejecutando pruebas..."'
                // Execute some commands to test pipeline
            }
        }

        stage("Env Build Number"){
            steps{
                echo "The build number is ${env.BUILD_NUMBER}"
                echo "You can also use \${BUILD_NUMBER} -> ${BUILD_NUMBER}"                                                
            }
        }
    
        stage('Test2') {
            steps {
                sh 'echo "Comprobando que el contenedor Jenkins se está ejecutando en Docker"'
                sh '''
                    if docker ps --format '{{.Names}}' | grep -q 'jenkins-custom-test'; then
                        echo "El contenedor jenkins-custom-test existe."
                    else
                        echo "El contenedor no existe."
                        exit 1
                    fi
                '''
            }
        }
  
    }
 }